#define MOVE_LEFT 1
#define MOVE_UP 2
#define MOVE_RIGHT 3
#define MOVE_DOWN 4

#define EVEN_NUMBER 2
#define MINIMUM_ROWS 3

#define MISSING_PARAMETER 1
#define MALFORMED_INPUT 2
#define FIELD_TOO_SMALL 3
#define NONEXISTENT_SOLUTION 4
#define OUT_OF_MEMORY 5
#define CANNOT_CONTINUE 6
